sudo: false

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

language: groovy

jdk:
#- oraclejdk11
- openjdk8
#- openjdk11

# matrix:
#   include:
#     - jdk: oraclejdk11
#       before_install:
#         - rm "${JAVA_HOME}/lib/security/cacerts"
#         - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"

env:
- TERM=dumb

install: true

before_script:
  - ./gradlew --version

script:
  - ./gradlew test jacocoTestReport coveralls
