language: android

sudo: false

android:
  components:
    - platform-tools
    - build-tools-23.0.1
    - android-23
    - extra-android-support
  licenses:
    - '.+'

script:
 - ./gradlew clean testDebugUnitTest --stacktrace
    
notifications:
  email: false