dist: bionic
sudo: false

language: java
jdk:
  - oraclejdk13
  - openjdk13

services:
  - mongodb

install: ./gradlew assemble

cache:
  directories:
  - $HOME/.gradle

script: ./gradlew check --info --stacktrace
