dist: trusty
sudo: required  # for installing the SANE daemon
language: java
jdk:
  - oraclejdk8
  - openjdk8
  - openjdk11

# Works around an issue in Travis, see
# https://github.com/travis-ci/travis-ci/issues/5227.
#
# The fix below is due to @BanzaiMan, see
# https://github.com/travis-ci/travis-ci/issues/5227#issuecomment-165131913
addons:
  hosts:
    - test-host
  hostname: test-host

before_install:
  # Installs SANE for SaneSessionTest.
  - sudo apt-get update -q
  - sudo apt-get install sane-utils
  - sudo sed -i s/RUN=no/RUN=yes/ /etc/default/saned

  # Add a password to the test device.
  - sudo bash -c 'echo testuser:goodpass:test > /etc/sane.d/saned.users'
  - sudo /etc/init.d/saned start

script: ./gradlew check --info

after_success: ./gradlew jacocoTestReport coveralls

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

